default:
  dataconnection:
    use_DBcache: FALSE
    dbname: "opendata"
    host: '10.210.1.26'
    user:  !expr if(Sys.getenv("PG_MASTER_USER") == "") Sys.getenv("PG_READ_OPEN_USER") else Sys.getenv("PG_MASTER_USER")
    password: !expr if(Sys.getenv("PG_MASTER_PW") == "") Sys.getenv("PG_READ_OPEN_PW") else Sys.getenv("PG_MASTER_PW")
    port: 443

local_cache:
  dataconnection:
    use_DBcache: TRUE

shinyapps:
  dataconnection:
    use_DBcache: FALSE
    dbname: "opendata"
    host: 'Default-Base-NLB-67052e8837584997.elb.ap-southeast-2.amazonaws.com'
    user:  !expr Sys.getenv("PG_READ_OPEN_USER")
    password: !expr Sys.getenv("PG_READ_OPEN_PW")
    port: 5432

github:
  dataconnection:
    use_DBcache: FALSE
    dbname: "opendata"
    host: 'Default-Base-NLB-67052e8837584997.elb.ap-southeast-2.amazonaws.com'
    user:  !expr Sys.getenv("PG_MASTER_USER")
    password: !expr Sys.getenv("PG_MASTER_PW")
    port: 5432
